title: Products
template: products/show
layout: layout
blueprints: product
revisions: false
sort_dir: asc
date_behavior:
  past: public
  future: private
structure:
  root: false
  max_depth: 1
  tree: {  }
